# Generated by Django 4.2.13 on 2024-08-21 14:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bb',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
